const chapitre5_CM1 = {
  Mathématique: [
    {
      id: 1,
      title: "Multiplication à deux chiffres",
      question: "Calcule : 78 × 5 = ?",
      result: ["390"],
      infoErro: "La bonne réponse était : 390.",
      infosucces: "78 × 5 = 390. Bravo !",
      type: "input",
    },
    {
      id: 2,
      title: "Division avec reste",
      question: "Calcule : 145 ÷ 12, quel est le quotient ?",
      result: ["12"],
      infoErro: "La bonne réponse était : 12.",
      infosucces: "145 ÷ 12 = 12 avec un reste, le quotient est 12.",
      type: "input",
    },
    {
      id: 3,
      title: "Problème de partage",
      question:
        "Une classe a 120 crayons à répartir dans 10 boîtes. Combien de crayons par boîte ?",
      result: ["12"],
      infoErro: "La bonne réponse était : 12.",
      infosucces: "120 ÷ 10 = 12 crayons par boîte.",
      type: "input",
    },
    {
      id: 4,
      title: "Nombres premiers",
      question: "Le nombre 37 est-il un nombre premier ?",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, 37 est un nombre premier.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Suite numérique avancée",
      question: "Complète la suite : 2, 4, 8, 16, 32, __",
      result: ["64"],
      infoErro: "La bonne réponse était : 64.",
      infosucces: "Chaque nombre est multiplié par 2.",
      type: "input",
    },
  ],
  Français: [
    {
      id: 1,
      title: "Conjugaison - futur proche",
      question:
        "Conjugue le verbe 'aller' à la 1ère personne du pluriel au futur proche.",
      result: ["nous allons"],
      infoErro: "La bonne réponse était : nous allons.",
      infosucces: "Nous allons.",
      type: "input",
    },
    {
      id: 2,
      title: "Accord pluriel",
      question: "Quel est le pluriel de 'cheval' ?",
      result: ["chevaux"],
      infoErro: "La bonne réponse était : chevaux.",
      infosucces: "Le pluriel de 'cheval' est 'chevaux'.",
      type: "input",
    },
    {
      id: 3,
      title: "Synonyme",
      question: "Donne un synonyme du mot 'rapide'.",
      result: ["vite"],
      infoErro: "La bonne réponse était : vite.",
      infosucces: "« Vite » est un synonyme de « rapide ». ",
      type: "input",
    },
    {
      id: 4,
      title: "Phrase correcte ?",
      question: "La phrase « Elles vont au marché » est-elle correcte ?",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, la phrase est correcte.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Nature des mots",
      question: "Dans la phrase « Le vent souffle fort », quel est le verbe ?",
      result: ["souffle"],
      infoErro: "La bonne réponse était : souffle.",
      infosucces: "« souffle » est le verbe.",
      type: "input",
    },
  ],
};

export default chapitre5_CM1;
