const chapitre1_CM1 = {
  Mathématique: [
    {
      id: 1,
      title: "Multiplications posées simples",
      question: "Calcule : 24 × 3 = ?",
      result: ["72"],
      infoErro: "La bonne réponse était : 72.",
      infosucces: "24 × 3 = 72. Bravo !",
      type: "input",
    },
    {
      id: 2,
      title: "Division simple sans reste",
      question: "Calcule : 56 ÷ 7 = ?",
      result: ["8"],
      infoErro: "La bonne réponse était : 8.",
      infosucces: "56 ÷ 7 = 8. Bien joué !",
      type: "input",
    },
    {
      id: 3,
      title: "Problème de partage",
      question:
        "Une classe a 30 élèves et 6 tables. Combien d'élèves par table ?",
      result: ["5"],
      infoErro: "La bonne réponse était : 5.",
      infosucces: "30 ÷ 6 = 5 élèves par table.",
      type: "input",
    },
    {
      id: 4,
      title: "Nombres pairs ou impairs",
      question: "Le nombre 124 est-il pair ?",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "124 est un nombre pair.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Compléter la suite numérique",
      question: "Complète la suite : 2, 4, 8, 16, __",
      result: ["32"],
      infoErro: "La bonne réponse était : 32.",
      infosucces: "Chaque nombre est multiplié par 2.",
      type: "input",
    },
  ],
  Français: [
    {
      id: 1,
      title: "Conjugaison - présent",
      question:
        "Conjugue le verbe 'finir' à la 2ème personne du pluriel au présent.",
      result: ["finissez"],
      infoErro: "La bonne réponse était : finissez.",
      infosucces: "Vous finissez.",
      type: "input",
    },
    {
      id: 2,
      title: "Accord sujet-verbe",
      question: "La phrase « Les chats dort » est-elle correcte ?",
      result: ["faux"],
      infoErro: "La bonne réponse était : faux.",
      infosucces: "Le verbe doit être « dorment » au pluriel.",
      type: "booleen",
    },
    {
      id: 3,
      title: "Synonyme",
      question: "Donne un synonyme du mot 'rapide'.",
      result: ["vite"],
      infoErro: "La bonne réponse était : vite.",
      infosucces: "« Vite » est un synonyme de « rapide ». ",
      type: "input",
    },
    {
      id: 4,
      title: "Phrase correcte ?",
      question: "La phrase « Je vais à l’école » est-elle correcte ?",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, la phrase est correcte.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Nature des mots",
      question: "Dans la phrase « Le chien court vite », quel est le verbe ?",
      result: ["court"],
      infoErro: "La bonne réponse était : court.",
      infosucces: "« court » est le verbe.",
      type: "input",
    },
  ],
};

export default chapitre1_CM1;
