const chapitre3_CM1 = {
  Mathématique: [
    {
      id: 1,
      title: "Multiplication posée",
      question: "Calcule : 45 × 7 = ?",
      result: ["315"],
      infoErro: "La bonne réponse était : 315.",
      infosucces: "45 × 7 = 315. Bravo !",
      type: "input",
    },
    {
      id: 2,
      title: "Division avec reste",
      question: "Calcule : 99 ÷ 8, quel est le quotient ?",
      result: ["12"],
      infoErro: "La bonne réponse était : 12.",
      infosucces: "99 ÷ 8 = 12 avec un reste, le quotient est 12.",
      type: "input",
    },
    {
      id: 3,
      title: "Problème de partage",
      question:
        "Une boîte contient 72 crayons à répartir dans 9 trousses. Combien de crayons par trousse ?",
      result: ["8"],
      infoErro: "La bonne réponse était : 8.",
      infosucces: "72 ÷ 9 = 8 crayons par trousse.",
      type: "input",
    },
    {
      id: 4,
      title: "Nombres pairs et impairs",
      question: "Le nombre 137 est-il pair ?",
      result: ["faux"],
      infoErro: "La bonne réponse était : faux.",
      infosucces: "137 est un nombre impair.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Suite numérique",
      question: "Complète la suite : 3, 6, 9, 12, __",
      result: ["15"],
      infoErro: "La bonne réponse était : 15.",
      infosucces: "La suite augmente de 3 en 3.",
      type: "input",
    },
  ],
  Français: [
    {
      id: 1,
      title: "Conjugaison - futur simple",
      question:
        "Conjugue le verbe 'venir' à la 1ère personne du singulier au futur simple.",
      result: ["je viendrai"],
      infoErro: "La bonne réponse était : je viendrai.",
      infosucces: "Je viendrai.",
      type: "input",
    },
    {
      id: 2,
      title: "Accord sujet-verbe",
      question: "La phrase « Les filles est contentes » est-elle correcte ?",
      result: ["faux"],
      infoErro: "La bonne réponse était : faux.",
      infosucces: "Le verbe doit être « sont » au pluriel.",
      type: "booleen",
    },
    {
      id: 3,
      title: "Synonymes",
      question: "Donne un synonyme du mot 'grand'.",
      result: ["haut"],
      infoErro: "La bonne réponse était : haut.",
      infosucces: "« Haut » est un synonyme de « grand ». ",
      type: "input",
    },
    {
      id: 4,
      title: "Phrase correcte ?",
      question: "La phrase « Nous allons à la plage » est-elle correcte ?",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, la phrase est correcte.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Nature des mots",
      question: "Dans la phrase « La pluie tombe », quel est le verbe ?",
      result: ["tombe"],
      infoErro: "La bonne réponse était : tombe.",
      infosucces: "« tombe » est le verbe.",
      type: "input",
    },
  ],
};

export default chapitre3_CM1;
