const chapitre2_CM1 = {
  Mathématique: [
    {
      id: 1,
      title: "Multiplication à deux chiffres",
      question: "Calcule : 37 × 6 = ?",
      result: ["222"],
      infoErro: "La bonne réponse était : 222.",
      infosucces: "37 × 6 = 222. Bravo !",
      type: "input",
    },
    {
      id: 2,
      title: "Division avec reste",
      question: "Calcule : 85 ÷ 9, quel est le quotient ?",
      result: ["9"],
      infoErro: "La bonne réponse était : 9.",
      infosucces: "85 ÷ 9 = 9 avec un reste, le quotient est 9.",
      type: "input",
    },
    {
      id: 3,
      title: "Problème de partage",
      question:
        "Un fermier a 48 pommes à répartir dans 8 paniers. Combien de pommes par panier ?",
      result: ["6"],
      infoErro: "La bonne réponse était : 6.",
      infosucces: "48 ÷ 8 = 6 pommes par panier.",
      type: "input",
    },
    {
      id: 4,
      title: "Nombres premiers",
      question: "Le nombre 23 est-il un nombre premier ?",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, 23 est un nombre premier.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Suite numérique",
      question: "Complète la suite : 5, 10, 15, 20, __",
      result: ["25"],
      infoErro: "La bonne réponse était : 25.",
      infosucces: "La suite augmente de 5 en 5.",
      type: "input",
    },
  ],
  Français: [
    {
      id: 1,
      title: "Conjugaison - imparfait",
      question:
        "Conjugue le verbe 'avoir' à la 3ème personne du pluriel à l’imparfait.",
      result: ["avaient"],
      infoErro: "La bonne réponse était : avaient.",
      infosucces: "Ils/Elles avaient.",
      type: "input",
    },
    {
      id: 2,
      title: "Accord adjectif",
      question: "Quel est le féminin pluriel de 'heureux' ?",
      result: ["heureuses"],
      infoErro: "La bonne réponse était : heureuses.",
      infosucces: "Le féminin pluriel est 'heureuses'.",
      type: "input",
    },
    {
      id: 3,
      title: "Synonyme",
      question: "Donne un synonyme du mot 'content'.",
      result: ["heureux"],
      infoErro: "La bonne réponse était : heureux.",
      infosucces: "« Heureux » est un synonyme de « content ». ",
      type: "input",
    },
    {
      id: 4,
      title: "Phrase correcte ?",
      question: "La phrase « Ils va au parc » est-elle correcte ?",
      result: ["faux"],
      infoErro: "La bonne réponse était : faux.",
      infosucces: "Le verbe doit être 'vont' pour s’accorder avec 'Ils'.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Nature des mots",
      question: "Dans la phrase « Le chat dort », quel est le sujet ?",
      result: ["Le chat"],
      infoErro: "La bonne réponse était : Le chat.",
      infosucces: "« Le chat » est le sujet.",
      type: "input",
    },
  ],
};

export default chapitre2_CM1;
