const chapitre4_CM1 = {
  Mathématique: [
    {
      id: 1,
      title: "Multiplication à deux chiffres",
      question: "Calcule : 56 × 9 = ?",
      result: ["504"],
      infoErro: "La bonne réponse était : 504.",
      infosucces: "56 × 9 = 504. Bravo !",
      type: "input",
    },
    {
      id: 2,
      title: "Division avec reste",
      question: "Calcule : 123 ÷ 10, quel est le quotient ?",
      result: ["12"],
      infoErro: "La bonne réponse était : 12.",
      infosucces: "123 ÷ 10 = 12 avec un reste, le quotient est 12.",
      type: "input",
    },
    {
      id: 3,
      title: "Problème de partage",
      question:
        "Un sac contient 150 billes à répartir dans 15 boîtes. Combien de billes par boîte ?",
      result: ["10"],
      infoErro: "La bonne réponse était : 10.",
      infosucces: "150 ÷ 15 = 10 billes par boîte.",
      type: "input",
    },
    {
      id: 4,
      title: "Nombres premiers",
      question: "Le nombre 31 est-il un nombre premier ?",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, 31 est un nombre premier.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Suite numérique complexe",
      question: "Complète la suite : 1, 2, 4, 8, 16, __",
      result: ["32"],
      infoErro: "La bonne réponse était : 32.",
      infosucces: "Chaque nombre est multiplié par 2.",
      type: "input",
    },
  ],
  Français: [
    {
      id: 1,
      title: "Conjugaison - passé composé",
      question:
        "Conjugue le verbe 'faire' à la 3ème personne du singulier au passé composé.",
      result: ["il a fait"],
      infoErro: "La bonne réponse était : il a fait.",
      infosucces: "Il a fait.",
      type: "input",
    },
    {
      id: 2,
      title: "Accord adjectif",
      question: "Quel est le féminin singulier de 'petit' ?",
      result: ["petite"],
      infoErro: "La bonne réponse était : petite.",
      infosucces: "Le féminin singulier est 'petite'.",
      type: "input",
    },
    {
      id: 3,
      title: "Synonyme",
      question: "Donne un synonyme du mot 'triste'.",
      result: ["malheureux"],
      infoErro: "La bonne réponse était : malheureux.",
      infosucces: "« Malheureux » est un synonyme de « triste ». ",
      type: "input",
    },
    {
      id: 4,
      title: "Phrase correcte ?",
      question: "La phrase « Elles ont mangé » est-elle correcte ?",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, la phrase est correcte.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Nature des mots",
      question: "Dans la phrase « Le soleil brille », quel est le sujet ?",
      result: ["Le soleil"],
      infoErro: "La bonne réponse était : Le soleil.",
      infosucces: "« Le soleil » est le sujet.",
      type: "input",
    },
  ],
};

export default chapitre4_CM1;
