const chapitre2_CP2 = {
  Mathématique: [
    {
      id: 1,
      title: "Comparer des nombres",
      question: "5 est-il plus grand que 3 ?",
      result: "vrai",
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, 5 est plus grand que 3.",
      type: "booleen",
    },
    {
      id: 2,
      title: "Additions intermédiaires",
      question: "Combien font 7 + 5 ?",
      result: "12",
      infoErro: "La bonne réponse était : 12.",
      infosucces: "7 + 5 = 12. Bien joué !",
      type: "choix",
      option: ["13", "11", "12", "14", "10"],
    },
    {
      id: 3,
      title: "Soustraction simple",
      question: "Combien font 10 - 4 ?",
      result: "6",
      infoErro: "La bonne réponse était : 6.",
      infosucces: "10 - 4 = 6. Bravo !",
      type: "input",
    },
    {
      id: 4,
      title: "Comparer des résultats",
      question: "6 + 2 est-il égal à 9 ?",
      result: "faux",
      infoErro: "La bonne réponse était : faux.",
      infosucces: "Non, 6 + 2 = 8. Bien vu !",
      type: "booleen",
    },
    {
      id: 5,
      title: "Addition + Soustraction",
      question: "Combien font (5 + 4) - 2 ?",
      result: "7",
      infoErro: "La bonne réponse était : 7.",
      infosucces: "5 + 4 = 9, puis 9 - 2 = 7. Excellent !",
      type: "choix",
      option: ["6", "7", "8", "9", "5"],
    },
  ],
  Français: [
    {
      id: 1,
      title: "Vrai ou faux ?",
      question: "Le mot 'lune' commence par une voyelle.",
      result: "vrai",
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, 'lune' commence par la voyelle L.",
      type: "booleen",
    },
    {
      id: 2,
      title: "Les contraires",
      question: "Quel est le contraire de 'grand' ?",
      result: "petit",
      infoErro: "La bonne réponse était : petit.",
      infosucces: "'Petit' est le contraire de 'grand'.",
      type: "choix",
      option: ["haut", "petit", "beau", "lent", "rapide"],
    },
    {
      id: 3,
      title: "Identifier un mot",
      question: "Écris le mot pour désigner ce que l’on mange à midi.",
      result: "déjeuner",
      infoErro: "La bonne réponse était : déjeuner.",
      infosucces: "Oui, on mange le déjeuner à midi.",
      type: "input",
    },
    {
      id: 4,
      title: "Sens des phrases",
      question: "Le chat vole dans le ciel. Est-ce une phrase correcte ?",
      result: "faux",
      infoErro: "La bonne réponse était : faux.",
      infosucces: "Non, un chat ne peut pas voler !",
      type: "booleen",
    },
    {
      id: 5,
      title: "Compréhension de consigne",
      question: "Choisis l’objet qu’on utilise pour écrire.",
      result: "stylo",
      infoErro: "La bonne réponse était : stylo.",
      infosucces: "Oui, on écrit avec un stylo !",
      type: "choix",
      option: ["stylo", "chaise", "crayon", "table", "sac"],
    },
  ],
};

export default chapitre2_CP2;
