const chapitre5_CP2 = {
  Mathématique: [
    {
      id: 1,
      title: "Addition de dizaines",
      question: "Combien font 20 + 10 ?",
      result: ["30"],
      infoErro: "La bonne réponse était : 30.",
      infosucces: "20 + 10 = 30. Bien joué !",
      type: "choix",
      option: ["25", "20", "30", "40", "35"],
    },
    {
      id: 2,
      title: "Soustraction et réflexion",
      question: "Combien faut-il enlever à 15 pour obtenir 9 ?",
      result: ["6"],
      infoErro: "La bonne réponse était : 6.",
      infosucces: "15 - 6 = 9. Très bien !",
      type: "choix",
      option: ["5", "6", "7", "4", "3"],
    },
    {
      id: 3,
      title: "Calcul en deux étapes",
      question: "Combien font (10 + 5) - 3 ?",
      result: ["12"],
      infoErro: "La bonne réponse était : 12.",
      infosucces: "10 + 5 = 15, puis 15 - 3 = 12.",
      type: "input",
    },
    {
      id: 4,
      title: "Vrai ou faux ?",
      question: "12 est un multiple de 4.",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui ! 4 x 3 = 12.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Problème complexe",
      question:
        "Lina a 18 billes. Elle en donne 7 à son frère. Combien lui en reste-t-il ?",
      result: ["11"],
      infoErro: "La bonne réponse était : 11.",
      infosucces: "18 - 7 = 11. Bien joué !",
      type: "input",
    },
  ],
  Français: [
    {
      id: 1,
      title: "Genre des mots",
      question: "Le mot 'chaise' est-il féminin ?",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, on dit 'la chaise'.",
      type: "booleen",
    },
    {
      id: 2,
      title: "Singulier ou pluriel",
      question: "Le mot 'pommes' est au pluriel.",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "'Pommes' prend un -s, c’est bien le pluriel.",
      type: "booleen",
    },
    {
      id: 3,
      title: "Complément de phrase",
      question: "Complète : Le chien court ... la rue.",
      result: ["dans"],
      infoErro: "La bonne réponse était : dans.",
      infosucces: "Le chien court dans la rue. Bravo !",
      type: "choix",
      option: ["sous", "sur", "vers", "dans", "avec"],
    },
    {
      id: 4,
      title: "Orthographe",
      question: "Écris correctement le mot entendu : école",
      result: ["école"],
      infoErro: "La bonne réponse était : école.",
      infosucces: "Oui, école s’écrit comme ça.",
      type: "input",
    },
    {
      id: 5,
      title: "Compréhension logique",
      question: "Si Julie a froid, elle met ...",
      result: ["un manteau"],
      infoErro: "La bonne réponse était : un manteau.",
      infosucces: "Oui, quand on a froid, on met un manteau.",
      type: "input",
    },
  ],
};
export default chapitre5_CP2;
