const chapitre1_CP2 = {
  Mathématique: [
    {
      id: 1,
      title: "Nombres pairs",
      question: "Le nombre 4 est-il pair ?",
      result: "vrai",
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, 4 est un nombre pair.",
      type: "booleen",
    },
    {
      id: 2,
      title: "Additions simples",
      question: "Combien font 6 + 2 ?",
      result: "8",
      infoErro: "La bonne réponse était : 8.",
      infosucces: "6 + 2 = 8. Très bien !",
      type: "choix",
      option: ["6", "9", "10", "8", "7"],
    },
    {
      id: 3,
      title: "Additions avec retenue",
      question: "Combien font 9 + 3 ?",
      result: "12",
      infoErro: "La bonne réponse était : 12.",
      infosucces: "9 + 3 = 12. Bien joué !",
      type: "input",
    },
    {
      id: 4,
      title: "Compléments à 10",
      question: "Quel nombre faut-il ajouter à 4 pour faire 10 ?",
      result: "6",
      infoErro: "La bonne réponse était : 6.",
      infosucces: "4 + 6 = 10. Bravo !",
      type: "choix",
      option: ["6", "7", "5", "4", "3"],
    },
    {
      id: 5,
      title: "Petite énigme",
      question: "Si j’ai 3 billes et que j’en gagne 5, combien ai-je ?",
      result: "8",
      infoErro: "La bonne réponse était : 8.",
      infosucces: "Tu as maintenant 8 billes. Super !",
      type: "input",
    },
  ],
  Français: [
    {
      id: 1,
      title: "Les voyelles",
      question: "La lettre E est-elle une voyelle ?",
      result: "vrai",
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, E est une voyelle.",
      type: "booleen",
    },
    {
      id: 2,
      title: "L'ordre alphabétique",
      question: "Quelle lettre vient après G ?",
      result: "H",
      infoErro: "La bonne réponse était : H.",
      infosucces: "Après G vient H dans l’alphabet.",
      type: "choix",
      option: ["F", "H", "I", "K", "L"],
    },
    {
      id: 3,
      title: "Reconnaître les sons",
      question: "Quel mot commence par le son [ch] ?",
      result: "chaise",
      infoErro: "La bonne réponse était : chaise.",
      infosucces: "Chaise commence par le son [ch]. Bravo !",
      type: "choix",
      option: ["table", "chaise", "lampe", "soleil", "gomme"],
    },
    {
      id: 4,
      title: "Écriture de mots",
      question: "Écris le mot qui désigne un animal qui miaule.",
      result: "chat",
      infoErro: "La bonne réponse était : chat.",
      infosucces: "Oui ! Le chat miaule. Bien joué !",
      type: "input",
    },
    {
      id: 5,
      title: "Compréhension de phrase",
      question: "Le soleil brille dans le ciel. Est-ce une phrase ?",
      result: "vrai",
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui ! C’est une phrase complète.",
      type: "booleen",
    },
  ],
};

export default chapitre1_CP2;
