const chapitre3_CP2 = {
  Mathématique: [
    {
      id: 1,
      title: "Vrai ou faux ?",
      question: "Le nombre 10 est plus grand que 7.",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, 10 est bien plus grand que 7.",
      type: "booleen",
    },
    {
      id: 2,
      title: "Additions complexes",
      question: "Combien font 8 + 7 ?",
      result: ["15"],
      infoErro: "La bonne réponse était : 15.",
      infosucces: "8 + 7 = 15. Bravo !",
      type: "choix",
      option: ["13", "15", "16", "14", "12"],
    },
    {
      id: 3,
      title: "Soustraction simple",
      question: "Combien font 14 - 6 ?",
      result: ["8"],
      infoErro: "La bonne réponse était : 8.",
      infosucces: "14 - 6 = 8. Bien joué !",
      type: "input",
    },
    {
      id: 4,
      title: "Comparer deux calculs",
      question: "Est-ce que 5 + 4 = 6 + 3 ?",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui ! 5 + 4 et 6 + 3 font tous deux 9.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Calcul réfléchi",
      question: "Combien faut-il ajouter à 11 pour obtenir 20 ?",
      result: ["9"],
      infoErro: "La bonne réponse était : 9.",
      infosucces: "11 + 9 = 20. Très bon calcul !",
      type: "choix",
      option: ["9", "8", "7", "6", "10"],
    },
  ],
  Français: [
    {
      id: 1,
      title: "Les mots outils",
      question: "Est-ce que 'le' est un mot outil ?",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, 'le' est un mot outil !",
      type: "booleen",
    },
    {
      id: 2,
      title: "Trouver le bon mot",
      question: "Quel mot complète : Le chat ... sur le lit.",
      result: ["dort"],
      infoErro: "La bonne réponse était : dort.",
      infosucces: "Le chat dort sur le lit. Bravo !",
      type: "choix",
      option: ["mange", "court", "dort", "marche", "saute"],
    },
    {
      id: 3,
      title: "Reconnaître les syllabes",
      question: "Combien de syllabes dans le mot 'papillon' ?",
      result: ["3"],
      infoErro: "La bonne réponse était : 3.",
      infosucces: "Pa-pi-llon : 3 syllabes. Très bien !",
      type: "input",
    },
    {
      id: 4,
      title: "Phrase correcte ?",
      question: "Marie mange une pomme rouge. Est-ce une phrase ?",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, c’est une phrase complète et correcte.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Compréhension de texte court",
      question: "Que fait Paul s’il est fatigué ? (réponse en un mot)",
      result: ["dort"],
      infoErro: "La bonne réponse était : dort.",
      infosucces: "Oui, Paul dort s’il est fatigué.",
      type: "input",
    },
  ],
};

export default chapitre3_CP2;
