const chapitre3_CM2 = {
  Mathématique: [
    {
      id: 1,
      title: "Division à deux chiffres",
      question: "Calcule : 864 ÷ 12 = ?",
      result: ["72"],
      infoErro: "La bonne réponse était : 72.",
      infosucces: "864 ÷ 12 = 72. Excellent !",
      type: "input",
    },
    {
      id: 2,
      title: "Multiplication à deux chiffres",
      question: "Calcule : 87 × 11 = ?",
      result: ["957"],
      infoErro: "La bonne réponse était : 957.",
      infosucces: "87 × 11 = 957. Bravo !",
      type: "input",
    },
    {
      id: 3,
      title: "Problème de proportionnalité",
      question: "Si 4 pommes coûtent 2 €, combien coûtent 10 pommes ?",
      result: ["5"],
      infoErro: "La bonne réponse était : 5.",
      infosucces: "10 pommes coûtent 5 €. Bien joué !",
      type: "input",
    },
    {
      id: 4,
      title: "Compléter une fraction",
      question: "Complète : 1/2 = ?/4",
      result: ["2"],
      infoErro: "La bonne réponse était : 2.",
      infosucces: "1/2 = 2/4, c'est correct.",
      type: "input",
    },
    {
      id: 5,
      title: "Nombre décimal",
      question: "Complète : 3 + 1,25 = ?",
      result: ["4.25"],
      infoErro: "La bonne réponse était : 4.25.",
      infosucces: "3 + 1,25 = 4,25.",
      type: "input",
    },
  ],
  Français: [
    {
      id: 1,
      title: "Conjugaison - imparfait",
      question:
        "Conjugue le verbe 'finir' à la 3e personne du pluriel à l'imparfait.",
      result: ["ils finissaient"],
      infoErro: "La bonne réponse était : ils finissaient.",
      infosucces: "Ils finissaient. Bravo !",
      type: "input",
    },
    {
      id: 2,
      title: "Homophones grammaticaux",
      question: "Complète : « Tu ___ raison. » (a / as)",
      result: ["as"],
      infoErro: "La bonne réponse était : as.",
      infosucces: "Tu as raison. Parfait !",
      type: "input",
    },
    {
      id: 3,
      title: "Complément de phrase",
      question:
        "Dans la phrase « Il lit un livre dans le salon », où est le complément de lieu ?",
      result: ["dans le salon"],
      infoErro: "La bonne réponse était : dans le salon.",
      infosucces: "« dans le salon » indique le lieu.",
      type: "input",
    },
    {
      id: 4,
      title: "Phrase correcte ?",
      question: "La phrase « Elle est allée au cinéma » est-elle correcte ?",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, la phrase est correcte.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Sens d’un mot",
      question: "Que signifie « silencieux » ?",
      result: ["qui ne fait pas de bruit"],
      infoErro: "La bonne réponse était : qui ne fait pas de bruit.",
      infosucces: "Très bien ! Silencieux = qui ne fait pas de bruit.",
      type: "input",
    },
  ],
};

export default chapitre3_CM2;
