const CP1exercice3 = {
  Mathématique: [
    {
      id: 1,
      title: "Soustraction simple",
      question: "Combien font 5 - 2 ?",
      result: ["3"],
      infoErro: "La bonne réponse était : 3.",
      infosucces: "5 - 2 = 3. Tu peux enlever 2 objets de 5 !",
      type: "choix",
      option: ["1", "3", "4", "7", "2"],
    },
    {
      id: 2,
      title: "Soustraction simple",
      question: "Combien font 8 - 3 ?",
      result: ["5"],
      infoErro: "La bonne réponse était : 5.",
      infosucces: "8 - 3 = 5. Bravo !",
      type: "choix",
      option: ["6", "5", "4", "3", "2"],
    },
    {
      id: 3,
      title: "Soustraction simple",
      question: "7 - 4 = 3",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "C'est vrai ! 7 - 4 = 3.",
      type: "booleen",
    },
    {
      id: 4,
      title: "Soustraction simple",
      question: "Écris le résultat de 6 - 1",
      result: ["5"],
      infoErro: "La bonne réponse était : 5.",
      infosucces: "6 - 1 = 5. Parfait !",
      type: "input",
    },
    {
      id: 5,
      title: "Soustraction simple",
      question: "Combien font 9 - 4 ?",
      result: ["5"],
      infoErro: "La bonne réponse était : 5.",
      infosucces: "9 - 4 = 5. Tu peux compter à rebours !",
      type: "choix",
      option: ["4", "5", "6", "3", "7"],
    },
    {
      id: 6,
      title: "Soustraction simple",
      question: "Combien font 10 - 3 ?",
      result: ["7"],
      infoErro: "La bonne réponse était : 7.",
      infosucces: "10 - 3 = 7. Excellent !",
      type: "choix",
      option: ["6", "7", "8", "5", "9"],
    },
    {
      id: 7,
      title: "Soustraction simple",
      question: "4 - 4 = 0",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "C'est vrai ! Quand on enlève tout, il reste 0.",
      type: "booleen",
    },
    {
      id: 8,
      title: "Soustraction simple",
      question: "Écris le résultat de 7 - 2",
      result: ["5"],
      infoErro: "La bonne réponse était : 5.",
      infosucces: "7 - 2 = 5. Très bien !",
      type: "input",
    },
    {
      id: 9,
      title: "Soustraction simple",
      question: "Combien font 6 - 3 ?",
      result: ["3"],
      infoErro: "La bonne réponse était : 3.",
      infosucces: "6 - 3 = 3. Tu as la moitié !",
      type: "choix",
      option: ["2", "3", "4", "1", "5"],
    },
    {
      id: 10,
      title: "Soustraction simple",
      question: "Écris le résultat de 5 - 5",
      result: ["0"],
      infoErro: "La bonne réponse était : 0.",
      infosucces: "5 - 5 = 0. Quand on enlève tout, il ne reste rien !",
      type: "input",
    },
  ],

  Français: [
    {
      id: 1,
      title: "Lecture de syllabes",
      question: "Lis cette syllabe : MA",
      result: ["ma"],
      infoErro: "La bonne réponse était : MA se lit 'ma'.",
      infosucces: "Bravo ! MA se lit bien 'ma' comme dans maman.",
      type: "choix",
      option: ["ma", "mi", "mo", "mu", "me"],
    },
    {
      id: 2,
      title: "Lecture de syllabes",
      question: "Comment se lit la syllabe : LI ?",
      result: "li",
      infoErro: "La bonne réponse était : LI se lit 'li'.",
      infosucces: "Excellent ! LI se lit 'li' comme dans livre.",
      type: "choix",
      option: ["la", "li", "lo", "le", "lu"],
    },
    {
      id: 3,
      title: "Lecture de syllabes",
      question: "La syllabe RO se lit 'ro'",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "C'est vrai ! RO se lit bien 'ro' comme dans robot.",
      type: "booleen",
    },
    {
      id: 4,
      title: "Lecture de syllabes",
      question: "Écris comment se lit la syllabe : PU",
      result: ["pu"],
      infoErro: "La bonne réponse était : pu.",
      infosucces: "Parfait ! PU se lit 'pu' comme dans puce.",
      type: "input",
    },
    {
      id: 5,
      title: "Lecture de syllabes",
      question: "Lis cette syllabe : SA",
      result: ["sa"],
      infoErro: "La bonne réponse était : SA se lit 'sa'.",
      infosucces: "Bravo ! SA se lit 'sa' comme dans sac.",
      type: "choix",
      option: ["si", "sa", "so", "su", "se"],
    },
    {
      id: 6,
      title: "Lecture de syllabes",
      question: "Comment se lit la syllabe : FE ?",
      result: ["fe"],
      infoErro: "La bonne réponse était : FE se lit 'fe'.",
      infosucces: "Très bien ! FE se lit 'fe' comme dans fée.",
      type: "choix",
      option: ["fa", "fi", "fo", "fu", "fe"],
    },
    {
      id: 7,
      title: "Lecture de syllabes",
      question: "La syllabe TO se lit 'to'",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "C'est juste ! TO se lit 'to' comme dans tomate.",
      type: "booleen",
    },
    {
      id: 8,
      title: "Lecture de syllabes",
      question: "Écris comment se lit la syllabe : BI",
      result: ["bi"],
      infoErro: "La bonne réponse était : bi.",
      infosucces: "Excellent ! BI se lit 'bi' comme dans biberon.",
      type: "input",
    },
    {
      id: 9,
      title: "Lecture de syllabes",
      question: "Lis cette syllabe : VO",
      result: ["vo"],
      infoErro: "La bonne réponse était : VO se lit 'vo'.",
      infosucces: "Super ! VO se lit 'vo' comme dans voiture.",
      type: "choix",
      option: ["va", "vi", "vo", "vu", "ve"],
    },
    {
      id: 10,
      title: "Lecture de syllabes",
      question: "Écris comment se lit la syllabe : NE",
      result: ["ne"],
      infoErro: "La bonne réponse était : ne.",
      infosucces: "Parfait ! NE se lit 'ne' comme dans nez.",
      type: "input",
    },
  ],
};
export default CP1exercice3;
