const CP1exercice1 = {
  Mathématique: [
    {
      id: 1,
      title: "Addition simple",
      question: "Combien font 2 + 3 ?",
      result: ["5"],
      infoErro: "La bonne réponse était : 5.",
      infosucces: "2 + 3 = 5. Bravo !",
      type: "choix",
      option: ["4", "5", "6", "3", "7"],
    },
    {
      id: 2,
      title: "Addition simple",
      question: "Combien font 1 + 4 ?",
      result: ["5"],
      infoErro: "La bonne réponse était : 5.",
      infosucces: "1 + 4 = 5. Tu progresses bien !",
      type: "choix",
      option: ["2", "5", "6", "1", "3"],
    },
    {
      id: 3,
      title: "Addition simple",
      question: "3 + 3 = 6",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, 3 + 3 = 6. Bien joué !",
      type: "booleen",
    },
    {
      id: 4,
      title: "Addition simple",
      question: "Écris le résultat de 4 + 2",
      result: ["6"],
      infoErro: "La bonne réponse était : 6.",
      infosucces: "4 + 2 = 6. Excellent !",
      type: "input",
    },
    {
      id: 5,
      title: "Addition simple",
      question: "Combien font 5 + 0 ?",
      result: ["5"],
      infoErro: "La bonne réponse était : 5.",
      infosucces: "5 + 0 = 5. Tu es super fort !",
      type: "choix",
      option: ["0", "10", "5", "6", "4"],
    },
  ],
  Français: [
    {
      id: 1,
      title: "Les voyelles et consonnes",
      question: "La lettre A est une voyelle",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces:
        "C'est vrai ! A est une voyelle. Les voyelles sont : A, E, I, O, U.",
      type: "booleen",
    },
    {
      id: 2,
      title: "Les voyelles et consonnes",
      question: "Quelle est la voyelle dans le mot 'chat' ?",
      result: ["a"],
      infoErro: "La bonne réponse était : A.",
      infosucces: "Bravo ! Dans 'chat', la voyelle est A.",
      type: "choix",
      option: ["c", "h", "a", "t", "i"],
    },
    {
      id: 3,
      title: "Les voyelles et consonnes",
      question: "La lettre M est une consonne",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces:
        "C'est juste ! M est une consonne. Toutes les lettres qui ne sont pas A, E, I, O, U sont des consonnes.",
      type: "booleen",
    },
    {
      id: 4,
      title: "Les voyelles et consonnes",
      question: "Écris la voyelle que tu entends dans 'lit'",
      result: ["i"],
      infoErro: "La bonne réponse était : i.",
      infosucces: "Parfait ! Dans 'lit', on entend la voyelle I.",
      type: "input",
    },
    {
      id: 5,
      title: "Les voyelles et consonnes",
      question: "Combien y a-t-il de voyelles dans l'alphabet ?",
      result: ["5"],
      infoErro: "La bonne réponse était : 5.",
      infosucces: "Excellent ! Il y a 5 voyelles : A, E, I, O, U.",
      type: "choix",
      option: ["3", "4", "5", "6", "7"],
    },
    // {
    //   id: 6,
    //   title: "Les voyelles et consonnes",
    //   question: "Quelle lettre est une consonne ?",
    //   result: ["b"],
    //   infoErro: "La bonne réponse était : B.",
    //   infosucces: "Bravo ! B est une consonne.",
    //   type: "choix",
    //   option: ["a", "e", "b", "i", "o"],
    // },
    // {
    //   id: 7,
    //   title: "Les voyelles et consonnes",
    //   question: "La lettre O est une consonne",
    //   result: ["faux"],
    //   infoErro: "La bonne réponse était : faux.",
    //   infosucces: "C'est faux ! O est une voyelle, pas une consonne.",
    //   type: "booleen",
    // },
    // {
    //   id: 8,
    //   title: "Les voyelles et consonnes",
    //   question: "Écris une voyelle que tu connais",
    //   result: ["a", "e", "i", "o", "u"],
    //   infoErro: "Tu devais écrire une voyelle : A, E, I, O ou U.",
    //   infosucces: "Très bien ! Tu as écrit une voyelle correctement.",
    //   type: "input",
    // },
    // {
    //   id: 9,
    //   title: "Les voyelles et consonnes",
    //   question: "Dans le mot 'bus', quelle est la voyelle ?",
    //   result: ["u"],
    //   infoErro: "La bonne réponse était : U.",
    //   infosucces: "Super ! Dans 'bus', la voyelle est U.",
    //   type: "choix",
    //   option: ["b", "u", "s", "a", "e"],
    // },
    // {
    //   id: 10,
    //   title: "Les voyelles et consonnes",
    //   question: "Écris la première voyelle de l'alphabet",
    //   result: ["a"],
    //   infoErro: "La bonne réponse était : a.",
    //   infosucces: "Parfait ! A est bien la première voyelle de l'alphabet.",
    //   type: "input",
    // },
  ],
};

export default CP1exercice1;
