const CP1exercice4 = {
  Mathématique: [
    {
      id: 1,
      title: "Les formes géométriques",
      question: "Observe cette forme : 🔺. Comment s'appelle-t-elle ?",
      result: "triangle",
      infoErro: "La bonne réponse était : triangle.",
      infosucces: "Bravo ! Cette forme 🔺 avec 3 côtés s'appelle un triangle.",
      type: "choix",
      option: ["carré", "triangle", "cercle", "rectangle", "losange"],
    },
    {
      id: 2,
      title: "Les formes géométriques",
      question: "Un carré 🟦 a 4 côtés égaux",
      result: "vrai",
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "C'est vrai ! Un carré 🟦 a 4 côtés de la même longueur.",
      type: "booleen",
    },
    {
      id: 3,
      title: "Les formes géométriques",
      question: "Combien de côtés a cette forme : ⬜ ?",
      result: 4,
      infoErro: "La bonne réponse était : 4.",
      infosucces: "Excellent ! Un rectangle ⬜ a 4 côtés.",
      type: "choix",
      option: ["2", "3", "4", "5", "6"],
    },
    {
      id: 4,
      title: "Les formes géométriques",
      question: "Écris le nom de cette forme ronde : ⚪",
      result: "cercle",
      infoErro: "La bonne réponse était : cercle.",
      infosucces: "Parfait ! Cette forme ronde ⚪ s'appelle un cercle.",
      type: "input",
    },
    {
      id: 5,
      title: "Les formes géométriques",
      question: "Cette forme 🔴 ressemble à quelle forme géométrique ?",
      result: "cercle",
      infoErro: "La bonne réponse était : cercle.",
      infosucces: "Bravo ! Cette forme 🔴 est ronde comme un cercle.",
      type: "choix",
      option: ["carré", "triangle", "cercle", "rectangle", "losange"],
    },
    {
      id: 6,
      title: "Les formes géométriques",
      question: "Un triangle 🔺 a des coins",
      result: "vrai",
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "C'est vrai ! Un triangle 🔺 a 3 coins (ou sommets).",
      type: "booleen",
    },
    {
      id: 7,
      title: "Les formes géométriques",
      question: "Quelle est cette forme : 🟨 ?",
      result: "carré",
      infoErro: "La bonne réponse était : carré.",
      infosucces: "Très bien ! Cette forme 🟨 est un carré avec 4 côtés égaux.",
      type: "choix",
      option: ["carré", "triangle", "cercle", "rectangle", "losange"],
    },
    {
      id: 8,
      title: "Les formes géométriques",
      question: "Un cercle ⚪ a des côtés",
      result: "faux",
      infoErro: "La bonne réponse était : faux.",
      infosucces:
        "C'est faux ! Un cercle ⚪ n'a pas de côtés, il est tout rond.",
      type: "booleen",
    },
    {
      id: 9,
      title: "Les formes géométriques",
      question: "Écris combien de côtés a cette forme : 🟩",
      result: "4",
      infoErro: "La bonne réponse était : 4.",
      infosucces: "Super ! Cette forme 🟩 (carré) a bien 4 côtés égaux.",
      type: "input",
    },
    {
      id: 10,
      title: "Les formes géométriques",
      question: "Observe : 🔸. Cette forme ressemble à quel objet ?",
      result: "losange",
      infoErro: "La bonne réponse était : losange.",
      infosucces: "Excellent ! Cette forme 🔸 s'appelle un losange.",
      type: "choix",
      option: ["carré", "triangle", "cercle", "rectangle", "losange"],
    },
  ],

  Français: [
    {
      id: 1,
      title: "Premiers mots",
      question: "Lis ce mot : PAPA",
      result: "papa",
      infoErro: "La bonne réponse était : papa.",
      infosucces: "Bravo ! Tu as bien lu PAPA. P-A-P-A = papa.",
      type: "choix",
      option: ["maman", "papa", "bébé", "chat", "eau"],
    },
    {
      id: 2,
      title: "Premiers mots",
      question: "Le mot MAMAN commence par la lettre M",
      result: "vrai",
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "C'est vrai ! MAMAN commence bien par la lettre M.",
      type: "booleen",
    },
    {
      id: 3,
      title: "Premiers mots",
      question: "Lis ce mot : CHAT 🐱",
      result: "chat",
      infoErro: "La bonne réponse était : chat.",
      infosucces: "Excellent ! Tu as lu CHAT. C-H-A-T = chat 🐱.",
      type: "choix",
      option: ["chien", "chat", "oiseau", "rat", "poule"],
    },
    {
      id: 4,
      title: "Premiers mots",
      question: "Écris le mot pour dire 'bonjour' quand on se couche",
      result: "bonsoir",
      infoErro: "La bonne réponse était : bonsoir.",
      infosucces: "Parfait ! Le soir on dit 'bonsoir' pour saluer.",
      type: "input",
    },
    {
      id: 5,
      title: "Premiers mots",
      question: "Quel mot désigne cette image : 🌞 ?",
      result: "soleil",
      infoErro: "La bonne réponse était : soleil.",
      infosucces: "Bravo ! 🌞 c'est le soleil qui brille dans le ciel.",
      type: "choix",
      option: ["lune", "soleil", "nuage", "étoile", "ciel"],
    },
    {
      id: 6,
      title: "Premiers mots",
      question: "Le mot ÉCOLE a 5 lettres",
      result: "vrai",
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "C'est vrai ! ÉCOLE : É-C-O-L-E = 5 lettres.",
      type: "booleen",
    },
    {
      id: 7,
      title: "Premiers mots",
      question: "Lis ce mot : BÉBÉ 👶",
      result: "bébé",
      infoErro: "La bonne réponse était : bébé.",
      infosucces: "Très bien ! Tu as lu BÉBÉ. B-É-B-É = bébé 👶.",
      type: "choix",
      option: ["papa", "maman", "bébé", "enfant", "petit"],
    },
    {
      id: 8,
      title: "Premiers mots",
      question: "Écris le mot qui désigne l'animal : 🐕",
      result: "chien",
      infoErro: "La bonne réponse était : chien.",
      infosucces: "Super ! 🐕 c'est un chien, le meilleur ami de l'homme.",
      type: "input",
    },
    {
      id: 9,
      title: "Premiers mots",
      question: "Quel mot dit-on pour saluer le matin ?",
      result: "bonjour",
      infoErro: "La bonne réponse était : bonjour.",
      infosucces: "Excellent ! Le matin on dit 'bonjour' pour saluer.",
      type: "choix",
      option: ["bonsoir", "bonjour", "salut", "coucou", "au revoir"],
    },
    {
      id: 10,
      title: "Premiers mots",
      question: "Écris le mot qui désigne ce qu'on boit : 💧",
      result: "eau",
      infoErro: "La bonne réponse était : eau.",
      infosucces: "Parfait ! 💧 c'est de l'eau, indispensable pour vivre.",
      type: "input",
    },
  ],
};

export default CP1exercice4;
