const CP1exercice2 = {
  Mathématique: [
    {
      id: 1,
      title: "Les nombres de 0 à 10",
      question: "Combien font 3 + 2 ?",
      result: ["5"],
      infoErro: "La bonne réponse était : 5.",
      infosucces: "3 + 2 = 5. Tu peux compter sur tes doigts !",
      type: "choix",
      option: ["4", "8", "6", "7", "5"],
    },
    {
      id: 2,
      title: "Les nombres de 0 à 10",
      question: "Quel nombre vient après 7 ?",
      result: ["8"],
      infoErro: "La bonne réponse était : 8.",
      infosucces: "Après 7 vient 8 dans l'ordre des nombres.",
      type: "choix",
      option: ["10", "8", "6", "9", "5"],
    },
    {
      id: 3,
      title: "Les nombres de 0 à 10",
      question: "5 est plus grand que 3",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "C'est vrai ! 5 est plus grand que 3.",
      type: "booleen",
    },
    {
      id: 4,
      title: "Les nombres de 0 à 10",
      question: "Écris le nombre qui vient avant 6",
      result: ["5"],
      infoErro: "La bonne réponse était : 5.",
      infosucces: "Le nombre qui vient avant 6 est 5.",
      type: "input",
    },
    {
      id: 5,
      title: "Les nombres de 0 à 10",
      question: "Combien font 4 + 1?",
      result: ["5"],
      infoErro: "La bonne réponse était : 5.",
      infosucces: "4 + 1 = 5. Bravo !",
      type: "choix",
      option: ["4", "8", "6", "7", "5"],
    },
  ],

  Français: [
    {
      id: 1,
      title: "Les lettres de l’alphabet",
      question: "Quelle lettre vient après B ?",
      result: ["C"],
      infoErro: "La bonne réponse était : C.",
      infosucces: "Bravo ! Après B vient C dans l’alphabet.",
      type: "choix",
      option: ["D", "A", "E", "C", "F"],
    },
    {
      id: 2,
      title: "Les lettres de l’alphabet",
      question: "La lettre A est-elle une voyelle ?",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui ! A est une voyelle.",
      type: "booleen",
    },
    {
      id: 3,
      title: "Les lettres de l’alphabet",
      question: "Écris la première lettre de l’alphabet",
      result: ["A"],
      infoErro: "La bonne réponse était : A.",
      infosucces: "A est la première lettre de l’alphabet.",
      type: "input",
    },
    {
      id: 4,
      title: "Les lettres de l’alphabet",
      question: "Quelle lettre vient avant D ?",
      result: ["C"],
      infoErro: "La bonne réponse était : C.",
      infosucces: "Bien joué ! Avant D, il y a C.",
      type: "choix",
      option: ["B", "C", "E", "F", "G"],
    },
    {
      id: 5,
      title: "Les lettres de l’alphabet",
      question: "Z est la dernière lettre de l’alphabet",
      result: ["vrai"],
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui ! L’alphabet se termine par Z.",
      type: "booleen",
    },
  ],
};
export default CP1exercice2;
