const chapitre2_CE1 = {
  Mathématique: [
    {
      id: 1,
      title: "Addition simple avec retenue",
      question: "Combien font 9 + 4 ?",
      result: "13",
      infoErro: "La bonne réponse était : 13.",
      infosucces: "9 + 4 = 13. Bien joué !",
      type: "choix",
      option: ["12", "13", "14", "15", "10"],
    },
    {
      id: 2,
      title: "Soustraction intermédiaire",
      question: "Combien font 17 - 9 ?",
      result: "8",
      infoErro: "La bonne réponse était : 8.",
      infosucces: "17 - 9 = 8. Bravo !",
      type: "input",
    },
    {
      id: 3,
      title: "Trouve le bon nombre",
      question: "Quel nombre complète : __ - 6 = 10",
      result: 16,
      infoErro: "La bonne réponse était : 16.",
      infosucces: "16 - 6 = 10. Parfait !",
      type: "input",
    },
    {
      id: 4,
      title: "Calcul en deux étapes",
      question: "Combien font (5 + 8) + 2 ?",
      result: "15",
      infoErro: "La bonne réponse était : 15.",
      infosucces: "5 + 8 = 13, puis 13 + 2 = 15.",
      type: "input",
    },
    {
      id: 5,
      title: "Quel est le plus petit ?",
      question: "Quel est le plus petit nombre ?",
      result: "23",
      infoErro: "La bonne réponse était : 23.",
      infosucces: "23 est le plus petit des choix proposés.",
      type: "choix",
      option: ["30", "25", "27", "29", "23"],
    },
  ],
  Français: [
    {
      id: 1,
      title: "Phrase à corriger",
      question:
        "La phrase suivante est-elle correcte ? « Il mangent une pomme. »",
      result: "faux",
      infoErro: "La bonne réponse était : faux.",
      infosucces: "On dit « Il mange » ou « Ils mangent », pas « Il mangent ».",
      type: "booleen",
    },
    {
      id: 2,
      title: "Choisir un verbe",
      question: "Complète : Le chien __ la balle.",
      result: "attrape",
      infoErro: "La bonne réponse était : attrape.",
      infosucces: "Le chien attrape la balle.",
      type: "choix",
      option: ["mange", "lit", "attrape", "ouvre", "monte"],
    },
    {
      id: 3,
      title: "Compréhension de phrase",
      question: "Lis : « Léo met ses chaussures rouges. » Que met Léo ?",
      result: "chaussures",
      infoErro: "La bonne réponse était : chaussures.",
      infosucces: "Léo met ses chaussures rouges. Bien lu !",
      type: "input",
    },
    {
      id: 4,
      title: "Nom ou adjectif ?",
      question: "Le mot 'jolie' est-il un adjectif ?",
      result: "vrai",
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, 'jolie' décrit un nom. C’est un adjectif.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Phrase logique",
      question: "Laquelle de ces phrases a du sens ?",
      result: "La souris mange du fromage.",
      infoErro: "La bonne réponse était : La souris mange du fromage.",
      infosucces: "C’est bien une phrase logique.",
      type: "choix",
      option: [
        "Le nuage boit un verre.",
        "La chaise court vite.",
        "La souris mange du fromage.",
        "L’arbre chante une chanson.",
        "La voiture dort.",
      ],
    },
  ],
};

export default chapitre2_CE1;
