const chapitre5_CE1 = {
  Mathématique: [
    {
      id: 1,
      title: "Soustraction avec petits nombres",
      question: "Combien font 14 - 5 ?",
      result: ["9"],
      infoErro: "La bonne réponse était : 9.",
      infosucces: "14 - 5 = 9. Bravo !",
      type: "input",
    },
    {
      id: 2,
      title: "Addition et comparaison",
      question: "Quel est le plus grand : 12 + 7 ou 18 ?",
      result: ["19"],
      infoErro: "La bonne réponse était : 19.",
      infosucces: "12 + 7 = 19, qui est plus grand que 18.",
      type: "input",
    },
    {
      id: 3,
      title: "Compléter la suite de nombres",
      question: "Complète : 10, 20, 30, __, 50",
      result: ["40"],
      infoErro: "La bonne réponse était : 40.",
      infosucces: "La suite augmente de 10 en 10, donc 40 est correct.",
      type: "input",
    },
    {
      id: 4,
      title: "Problème simple",
      question:
        "Paul a 15 billes, il en donne 7 à son frère. Combien lui reste-t-il ?",
      result: ["8"],
      infoErro: "La bonne réponse était : 8.",
      infosucces: "15 - 7 = 8. Bien joué !",
      type: "input",
    },
    {
      id: 5,
      title: "Multiples de 3",
      question: "Quel nombre est un multiple de 3 ?",
      result: ["18"],
      infoErro: "La bonne réponse était : 18.",
      infosucces: "18 est un multiple de 3.",
      type: "choix",
      option: ["16", "17", "19", "18", "20"],
    },
  ],
  Français: [
    {
      id: 1,
      title: "Trouver le verbe",
      question: "Dans la phrase « La fille chante », quel est le verbe ?",
      result: ["chante"],
      infoErro: "La bonne réponse était : chante.",
      infosucces: "« chante » est le verbe.",
      type: "input",
    },
    {
      id: 2,
      title: "Singulier ou pluriel ?",
      question: "Le mot 'fleurs' est-il au singulier ou au pluriel ?",
      result: ["pluriel"],
      infoErro: "La bonne réponse était : pluriel.",
      infosucces: "« fleurs » est au pluriel.",
      type: "choix",
      option: ["singulier", "pluriel"],
    },
    {
      id: 3,
      title: "Compréhension",
      question: "Que fait le chat dans « Le chat dort sur le tapis » ?",
      result: ["dort"],
      infoErro: "La bonne réponse était : dort.",
      infosucces: "Le chat dort sur le tapis.",
      type: "input",
    },
    {
      id: 4,
      title: "Phrase correcte ?",
      question: "Est-ce que cette phrase est correcte : « Les oiseaux vole » ?",
      result: ["faux"],
      infoErro: "La bonne réponse était : faux.",
      infosucces: "Il faut dire « Les oiseaux volent ».",
      type: "booleen",
    },
    {
      id: 5,
      title: "Trouver l’adjectif",
      question: "Quel mot est un adjectif dans cette liste ?",
      result: ["petit"],
      infoErro: "La bonne réponse était : petit.",
      infosucces: "« petit » est un adjectif.",
      type: "choix",
      option: ["chien", "courir", "petit", "manger", "maison"],
    },
  ],
};

export default chapitre5_CE1;
