const chapitre1_CE1 = {
  Mathématique: [
    {
      id: 1,
      title: "Trouve le nombre manquant",
      question: "4 + __ = 9",
      result: "5",
      infoErro: "La bonne réponse était : 5.",
      infosucces: "Oui, 4 + 5 = 9. Bien joué !",
      type: "input",
    },
    {
      id: 2,
      title: "Doubles",
      question: "Quel est le double de 7 ?",
      result: "14",
      infoErro: "La bonne réponse était : 14.",
      infosucces: "Le double de 7, c’est 14.",
      type: "choix",
      option: ["12", "13", "14", "15", "16"],
    },
    {
      id: 3,
      title: "Suite logique",
      question: "Complète la suite : 2, 4, 6, __, 10",
      result: "8",
      infoErro: "La bonne réponse était : 8.",
      infosucces: "La suite compte de 2 en 2. 8 est le bon nombre.",
      type: "input",
    },
    {
      id: 4,
      title: "Petit problème",
      question:
        "Emma a 5 billes. Elle en gagne 3 puis en perd 2. Combien en a-t-elle ?",
      result: "6",
      infoErro: "La bonne réponse était : 6.",
      infosucces: "5 + 3 = 8, puis 8 - 2 = 6. Bravo !",
      type: "input",
    },
    {
      id: 5,
      title: "Comparer",
      question: "Lequel est le plus grand ?",
      result: "19",
      infoErro: "La bonne réponse était : 19.",
      infosucces: "Oui, 19 est le plus grand nombre.",
      type: "choix",
      option: ["17", "12", "16", "19", "15"],
    },
  ],
  Français: [
    {
      id: 1,
      title: "Complète la phrase",
      question: "Le chat __ sur le canapé.",
      result: "dort",
      infoErro: "La bonne réponse était : dort.",
      infosucces: "Le chat dort sur le canapé. Bien joué !",
      type: "choix",
      option: ["mange", "dort", "lit", "saute", "crie"],
    },
    {
      id: 2,
      title: "Compréhension",
      question:
        "Lis : « Léa mange une pomme rouge. » Quelle couleur est la pomme ?",
      result: "rouge",
      infoErro: "La bonne réponse était : rouge.",
      infosucces: "La phrase dit bien que la pomme est rouge.",
      type: "input",
    },
    {
      id: 3,
      title: "Mot inapproprié",
      question: "Quel mot ne va pas avec les autres ?",
      result: "chaise",
      infoErro: "La bonne réponse était : chaise.",
      infosucces: "Les autres sont des animaux, pas chaise.",
      type: "choix",
      option: ["chien", "chat", "lapin", "chaise", "souris"],
    },
    {
      id: 4,
      title: "Vrai ou faux ?",
      question: "Le mot 'bleu' est un nom.",
      result: "faux",
      infoErro: "La bonne réponse était : faux.",
      infosucces: "Non, 'bleu' est un adjectif ici.",
      type: "booleen",
    },
    {
      id: 5,
      title: "Genre du mot",
      question: "Le mot 'voiture' est-il féminin ?",
      result: "vrai",
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, on dit *la* voiture.",
      type: "booleen",
    },
  ],
};
export default chapitre1_CE1;
