const chapitre4_CE1 = {
  Mathématique: [
    {
      id: 1,
      title: "Addition avec retenue",
      question: "Combien font 18 + 7 ?",
      result: "25",
      infoErro: "La bonne réponse était : 25.",
      infosucces: "18 + 7 = 25. Bravo !",
      type: "input",
    },
    {
      id: 2,
      title: "Soustraction avec nombres pairs",
      question: "Combien font 20 - 14 ?",
      result: "6",
      infoErro: "La bonne réponse était : 6.",
      infosucces: "20 - 14 = 6. Bien joué !",
      type: "input",
    },
    {
      id: 3,
      title: "Compléter la suite",
      question: "Complète la suite : 3, 6, 9, __, 15",
      result: "12",
      infoErro: "La bonne réponse était : 12.",
      infosucces: "La suite augmente de 3 en 3, donc 12 est correct.",
      type: "input",
    },
    {
      id: 4,
      title: "Problème avec achats",
      question:
        "Marie a 30 euros. Elle achète un jouet à 12 euros. Combien lui reste-t-il ?",
      result: "18",
      infoErro: "La bonne réponse était : 18.",
      infosucces: "30 - 12 = 18. Très bien !",
      type: "input",
    },
    {
      id: 5,
      title: "Comparer deux nombres",
      question: "Lequel est plus grand ?",
      result: "42",
      infoErro: "La bonne réponse était : 42.",
      infosucces: "42 est plus grand que les autres nombres proposés.",
      type: "choix",
      option: ["35", "40", "42", "39", "38"],
    },
  ],
  Français: [
    {
      id: 1,
      title: "Identifier le nom",
      question: "Dans la phrase « Le chien court vite », quel est le nom ?",
      result: "chien",
      infoErro: "La bonne réponse était : chien.",
      infosucces: "« chien » est le nom.",
      type: "input",
    },
    {
      id: 2,
      title: "Trouver le féminin",
      question: "Quel est le féminin de 'acteur' ?",
      result: "actrice",
      infoErro: "La bonne réponse était : actrice.",
      infosucces: "Le féminin d'acteur est actrice.",
      type: "input",
    },
    {
      id: 3,
      title: "Vrai ou faux ?",
      question: "La phrase « Les enfants jouent dehors » est correcte.",
      result: "vrai",
      infoErro: "La bonne réponse était : vrai.",
      infosucces: "Oui, la phrase est correcte.",
      type: "booleen",
    },
    {
      id: 4,
      title: "Compléter avec un adjectif",
      question: "Complète : Le soleil est __.",
      result: "brillant",
      infoErro: "La bonne réponse était : brillant.",
      infosucces: "Le soleil est brillant.",
      type: "choix",
      option: ["brillant", "rapide", "doux", "grand", "moche"],
    },
    {
      id: 5,
      title: "Phrase à corriger",
      question:
        "La phrase suivante est-elle correcte ? « Il a mange une pomme. »",
      result: "faux",
      infoErro: "La bonne réponse était : faux.",
      infosucces: "Il manque l’accent : « mangé ».",
      type: "booleen",
    },
  ],
};

export default chapitre4_CE1;
